services:
  aircraft-cache:
    build:
      target: development
    image: aircraft-cache-development
    container_name: aircraft-cache-development
    ports:
      - "9230:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    depends_on: 
      - aircraft-message
      - aircraft-redis
    environment:
      MESSAGE_HOST: aircraft-message
      MESSAGE_USERNAME: rabbitmq
      MESSAGE_PASSWORD: rabbitmq
      REDIS_HOST: aircraft-redis
    entrypoint: >
      sh -c "
        scripts/wait-for aircraft-message:5672 --
        npm run start:watch"

  aircraft-message:
    image: rabbitmq:3-management-alpine
    container_name: aircraft-message
    hostname: aircraft-message
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"

  aircraft-redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
