{{- include "helm-library.container-secret" (list . "aircraft-cache.container-secret") -}}
{{- define "aircraft-cache.container-secret" -}}
stringData:
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  MESSAGE_USERNAME: {{ quote .Values.container.messageUsername }}
  MESSAGE_PASSWORD: {{ quote .Values.container.messagePassword }}
{{- end -}}
