environment: production
name: aircraft-cache
image: aircraft-cache

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  redisHost:
  redisPassword:
  messageHost:
  messageUsername:
  messagePassword:
  messageExchange: aircraft-tracked
  messageQueue: aircraft-tracked-cache

deployment: {}

secret:
  type: Opaque
