environment: production
name: aircraft-cache
image: aircraft-cache

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  redisHost: services.lynxmagnus.com
  messageHost: services.lynxmagnus.com
  messageExchange: aircraft-tracked
  messageQueue: aircraft-tracked-cache

deployment: {}

secret:
  secretsPath: /aircraft-cache
